---
javascript:
    displayName: Javascript
    steps:
        - file: "wizard-app.js"
          highlight: "0-513"
        - file: "wizard-app.js"
          highlight: "11-69"
        - file: "wizard-app.js"
          highlight: "74-114"
        - file: "wizard-app.js"
          highlight: "120-125"
        - file: "wizard-app.js"
          highlight: "144-148"
        - file: "wizard-app.js"
          highlight: "154-167"
        - file: "wizard-app.js"
          highlight: "174-201"
        - file: "wizard-app.js"
          highlight: "294-301"
        - file: "wizard-app.js"
          highlight: "267-281"
        - file: "wizard-app.js"
          highlight: "315-328"
        - file: "wizard-app.js"
          highlight: "343-487"
        - file: "wizard-app.js"
          highlight: "359-387"
        - file: "wizard-app.js"
          highlight: "387-413"
        - file: "wizard-app.js"
          highlight: "413-459"
        - file: "index.html"
          highlight: "105-125"
        - file: "wizard-app.js"
          highlight: "203-262"